variables:
    TZ: "America/New_York"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    APT_CACHE_DIR: "$CI_PROJECT_DIR/apt-cache"
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
    FARADAY_USER: custom_user
    FARADAY_PASSWORD: custom_pass
    FARADAY_EMAIL: test@test.com
    FARADAY_URL: http://localhost:5985/
    DEFAULT_FARADAY_REF: white/dev
   # faraday devsecops
   # VAULT_ROLE: 'python-sast-readonly'
   # VAULT_ADDR: 'https://tluav-lb.faradaysec.com'
   # VAULT_SECRET_PATH: 'gitlab/SAST'    
    VAULT_SERVER_URL: https://tluav-lb.faradaysec.com
    VAULT_AUTH_ROLE: gorrabot
    VAULT_AUTH_PATH: jwt

include:
  - local: .gitlab/get-secret.yaml
# include:
#   - local: .gitlab/ci/fetch-secrets.yml

# workflow:
#   rules:
#     - if: $CI_MERGE_REQUEST_ID
#       when: never
#     - when: always

# cache:
#   paths:
#     - "$CI_PROJECT_DIR/.cache/pip"
#     - "$CI_PROJECT_DIR/apt-cache"


# before_script:
#     - mkdir -pv $APT_CACHE_DIR

stages:
    - deploy

deploy:
    stage: deploy
    environment: dev
    extends:
        - .get-secrets
    # Pull docker image
    image: python:3.8-bullseye
    # Setup AWS CLI to have proper credential keys
    before_script:
        - mkdir ~/.aws/
        - touch ~/.aws/credentials
        - apt-get update
        - apt-get install software-properties-common -y
        - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
        - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        - apt-get update && apt-get install vault -y
        - setcap cap_ipc_lock= /usr/bin/vault
        - KEY=$(cat $AWS_ACCESS_KEY_ID)
        - ACCESSK=$(cat $AWS_SECRET_ACCESS_KEY)
        - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$KEY" "$ACCESSK" >> ~/.aws/credentials
        - pip install awsebcli
    # Run deployment using EB CLI deploy on master branch
    script:
        - eb deploy gorrabot-dev
    # Ensure to run deployment only on master branch
    rules:
      - if: $CI_COMMIT_REF_NAME == "master"
        when: on_success
    tags:
        - faradaytests
