branch-defaults:
  test_aws:
    environment: gorrabot-dev
environment-defaults:
  gorrabot-dev:
    branch: master
    repository:
global:
  application_name: gorrabot-dev
  default_ec2_keyname: juanmac #debug
  default_platform: Python 3.9 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
